name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: SSH into server and run deployment commands
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r .next/* $VPS_USER@$VPS_IP:jobfynder/.next
          scp -o StrictHostKeyChecking=no -i private_key -r package.json $VPS_USER@$VPS_IP:jobfynder
          scp -o StrictHostKeyChecking=no -i private_key -r package-lock.json $VPS_USER@$VPS_IP:jobfynder
          ssh -o StrictHostKeyChecking=no -i private_key $VPS_USER@$VPS_IP "cd jobfynder && npm install --production && pm2 restart all"
